spring:
  cloud:
    nacos:
      discovery:
        #serverAddr: 127.0.0.1:8848
        server-addr: 192.168.1.219:8848
        namespace: b534b07e-c8f6-4320-b453-cc4780985c11
  #mysql
  datasource:
    url: jdbc:mysql://192.168.1.213:3306/dev_lbb_finance?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: dev_apps
    password: g9Jy3hMH
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true

  #redis
  redis:
    host: 192.168.1.223
    port: 6379
    password: redis_&lbb_0517
    pool:
      max-active: 200
      max-wait: 1
      max-idle: 10
      min-idle: 0
      timeout: 1000
  rabbitmq:
    host: 192.168.1.223
    username: guest
    password: guest
    virtual-host: /test
    listener:
      simple:
        # ????
        acknowledge-mode: manual
        retry:
          ####?????????
          enabled: true
          ####??????(????????3?)
          max-attempts: 5
          max-interval: 150000   # ????????
          initial-interval: 1000  # ????????
          multiplier: 3 # ?????????????*??=????????????????????????
  #swagger??
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
#mybatis??
mybatis:
  mapper-locations : classpath:mapper/*Mapper.xml